### ISSUE TITLE
机器人中断后怎么再次连接上。。。

### ISSUE THREAD

**Issue by bangxian** [BotTimeDocs/product-docs#239]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for academy.bottime.com ➟ GitHub issue linking.*

* ID: 93a746a0-678f-47fd-81d2-40b59d6d4c62

**Comment by WangXin008** [comment]
在控制台中，“RPA 管理 > 机器人管理”中，点击“操作”栏中的“查看”，复制“机器人连接字符串”至机器人中的“设置 > 关于”页，进行控制台激活时，粘贴已复制的字符串，便可连接。

若有问题，可以至论坛（https://forum.encoo.com/）提问，可以及时得到解决。
