### ISSUE TITLE
关于excel去重文档说明的错误

### ISSUE THREAD

**Issue by chanyihao** [BotTimeDocs/product-docs#246]
[Enter feedback here]
区域 ：查找操作的目标单元格区域。为空时，默认查找全表

企业版使用中，实际区域不能为空，需设置具体的区域比如A至C列"A:C"

---
#### Document Details

⚠ *Do not edit this section. It is required for academy.bottime.com ➟ GitHub issue linking.*

* ID: 72a8b9a3-62ef-4c7c-af2a-3545fd536898

**Comment by WangXin008** [comment]
“**去重**”组件的“区域”属性，是不允许为空的，请下载最新版本的编辑器进行使用。
