### ISSUE TITLE
”超时(毫秒) ：指定此组件的执行时间。单位为毫秒（ms）,1000ms = 1s。包含匹配超时（毫秒）。若超出此时间元素还【未】消失，会抛出错误。“ 少了一个字

### ISSUE THREAD

**Issue by amandameng** [BotTimeDocs/product-docs#247]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for academy.bottime.com ➟ GitHub issue linking.*

* ID: bb953f8c-184f-46ef-ae42-cb3084b29582

**Comment by WangXin008** [comment]
Fixed
