### ISSUE TITLE
文档中没有解释 输出

### ISSUE THREAD

**Issue by gangsir** [BotTimeDocs/product-docs#26]
解释一下什么是输出 变量的类型，以及如何定一个一个datatable的变量接收这个活动的结果。

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for academy.bottime.com ➟ GitHub issue linking.*

* ID: a712a541-f3b0-40cb-813f-77bb92e0a2a6

**Comment by liubingchi3** [comment]
云扩的整套产品是基于 C# 开发的，这边输入和输出填入的参数，都是 C# 中的一个数据类型。
比如如果要求填写 string 类型，那么你可以填写 string 类型的常量或变量。
对于一个组件的输出位置，需要有一个 dataTable 类型的变量去承接组件的运行结果时，你需要首先声明这个变量，再把变量名填写到组件的输出结果处。
定义变量的方式有两种，分别是：
- 在编辑器下方变量列表处，添加一个新的变量
- 在输出位置填写变量名，然后全选变量名，按快捷键 Ctrl + B 快速声明变量。
